[plugins]
licenser = { id = "org.cadixdev.licenser", version = "0.6.1" }
minecraftForge = { id = "net.minecraftforge.gradle", version = "5.1.34" }
librarian = { id = "org.parchmentmc.librarian.forgegradle", version = "1.2.0" }
mixin = { id = "org.spongepowered.mixin", version = "0.7.32" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }

[versions]
minecraft = "1.18.2"
forge = "40.1.0"
parchment = "2022.05.02"

[libraries]
minecraftForge.module = "net.minecraftforge:forge"
mixin = "org.spongepowered:mixin:0.8.5"
